variables:
    ArmTemplateRoot: '$(Build.SourcesDirectory)\Resources\ArmTemplates'     
    SolutionBaseName: 'DFC.App.JobProfile.CurrentOpportunities'
    BuildPlatform: 'any cpu'
    BuildConfiguration: 'release'

resources:
  repositories:
  - repository: self
  - repository: dfc-devops
    type: github
    name: SkillsFundingAgency/dfc-devops
    ref: refs/tags/v1.11.2
    endpoint: 'GitHub (ESFA)'

pool:
  name: NCS - CI and CD
  demands:
    - msbuild
    - visualstudio

jobs:

#Build and test resources
- job: BuildArmTemplates
  steps:
  - template: AzureDevOpsTemplates/Build/StepTemplates/dfc-arm-build.yml@dfc-devops
    parameters:
      ArmTemplateRoot: $(ArmTemplateRoot)

#Build and test application
- job: BuildDotNetCore
  displayName: Build-DotNetCore
  workspace:
    clean: all
  steps:
  # Build DFC.App.CurrentOpportunities
  - template: AzureDevOpsTemplates/Build/StepTemplates/dfc-dotnetcore-build-sonar.yml@dfc-devops
    parameters:
      SolutionBaseName: $(SolutionBaseName)
      BuildPlatform: $(BuildPlatform)
      BuildConfiguration: $(BuildConfiguration)
      PublishWebApp: true
      TestSuffix: UnitTests

  # Build DFC.App.CurrentOpportunities.MessageFunctionApp
  - template: AzureDevOpsTemplates/Build/StepTemplates/dfc-dotnetcore-build-notests.yml@dfc-devops
    parameters:
      SolutionBaseName: $(SolutionBaseName).MessageFunctionApp
      BuildPlatform: $(BuildPlatform)
      BuildConfiguration: $(BuildConfiguration)
      PublishWebApp: true

#Build integration tests
- job: BuildIntegrationTests
  displayName: Build integration tests
  steps:
  # Build all Integration Tests that end with .IntegrationTests
  - template: AzureDevOpsTemplates\Build\StepTemplates\dfc-dotnetcore-build-notests.yml@dfc-devops
    parameters:
      SolutionBaseName: $(SolutionBaseName).IntegrationTests
      BuildPlatform: $(BuildPlatform)
      BuildConfiguration: $(BuildConfiguration)

 #Build functional Tests
- job: Buildfunctionaltests
  displayName: Build functional tests
  steps:
  # Build all Functional Tests that ends with .FunctionalTests
  - template: AzureDevOpsTemplates\Build\StepTemplates\dfc-dotnetcore-build-sonar.yml@dfc-devops
    parameters:
      SolutionBaseName: $(SolutionBaseName).FunctionalTests
      BuildPlatform: $(BuildPlatform)
      BuildConfiguration: $(BuildConfiguration)
